DafuerGetOptGeneratorBundle_homepage:
    pattern:  /
    defaults: { _controller: DafuerGetOptGeneratorBundle:Default:index }
    
DafuerGetOptGeneratorBundle_moreinformation:
    pattern:  /more-information
    defaults: { _controller: DafuerGetOptGeneratorBundle:Default:moreinformation }

DafuerGetOptGeneratorBundle_start:
    pattern:  /start
    defaults: { _controller: DafuerGetOptGeneratorBundle:Default:start }

DafuerGetOptGeneratorBundle_project:
    resource: "@DafuerGetOptGeneratorBundle/Resources/config/routing/project.yml"
    prefix:   /project
    
#DafuerGetOptGeneratorBundle_projectoption:
#    resource: "@DafuerGetOptGeneratorBundle/Resources/config/routing/projectoption.yml"
#    prefix:   /projectoption

